#name: Build-Docker-Image-Workflow

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:

jobs:
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: contains(github.event.head_commit.message, '[docker to ecr]')
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        with:
          project-name: test-codebuild
          buildspec-override: .github/workflows/buildspec.yml
          env-vars-for-codebuild: |
            AWS_DEFAULT_REGION,
            AWS_ACCOUNT_ID,
            IMAGE_REPO_NAME,
            IMAGE_TAG,
            GITHUB_BRANCH_NAME
        env:
          AWS_DEFAULT_REGION: us-east-2
          AWS_ACCOUNT_ID: 505625506668
          IMAGE_REPO_NAME: testing-gh-actions #In ECR
          IMAGE_TAG: ${{ github.sha }}
          GITHUB_BRANCH_NAME: ${GITHUB_REF#refs/heads/}
          #GITHUB_BRANCH_NAME: main
